services:
  php:
    build:
      context: php-apache
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../site:/var/www/site
  db:
    image: mariadb:10.9.2
    restart: always
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    ports:
      - 3306:3306
    volumes:
      - ../database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST = db
      - PMA_ARBITRARY = 1
